# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:11
    restart: always
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: zhizhu
      POSTGRES_USER: zhizhu

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
